In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
from IPython.display import display

def membership_temp(x):
    return [max(0, min(1, (x - 20) / 10)), max(0, min(1, (30 - x) / 10))]

def membership_humidity(x):
    return [max(0, min(1, (x - 30) / 20)), max(0, min(1, (60 - x) / 20))]

def fuzzy_and(a, b):
    return min(a, b)

def fuzzy_or(a, b):
    return max(a, b)

def inference(temp, humidity):
    temp_low, temp_high = membership_temp(temp)
    humidity_low, humidity_high = membership_humidity(humidity)

    rule1 = fuzzy_and(temp_low, humidity_low)  # low temp and low humidity
    rule2 = fuzzy_and(temp_low, humidity_high)  # low temp and high humidity
    rule3 = fuzzy_and(temp_high, humidity_low)  # high temp and low humidity
    rule4 = fuzzy_and(temp_high, humidity_high)  # high temp and high humidity

    output = [rule1 * 20 + rule2 * 50 + rule3 * 70 + rule4 * 90]

    return output

def fuzzy_logic_system(temp_range, humidity_range):
    data = []

    for temp in temp_range:
        for humidity in humidity_range:
            output = inference(temp, humidity)
            data.append([temp, humidity, output[0]])

    df = pd.DataFrame(data, columns=["Temperature", "Humidity", "Output"])
    styled_df = df.style.format({
        "Temperature": "{:.2f}",
        "Humidity": "{:.2f}",
        "Output": "{:.2f}"
    }).background_gradient(cmap="viridis", axis=0).set_table_styles(
        [{'selector': 'thead th', 'props': [('background-color', '#4CAF50'), ('color', 'white')]},
         {'selector': 'tbody td', 'props': [('background-color', '#f9f9f9'), ('color', 'black')]},
         {'selector': 'tbody tr:nth-child(even)', 'props': [('background-color', '#f1f1f1')]},
         {'selector': 'tbody tr:hover', 'props': [('background-color', '#e2e2e2')]}]
    )

    display(styled_df)
    return df

df = fuzzy_logic_system(np.arange(10, 41, 5), np.arange(10, 101, 10))